# Deployment para PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment # Nombre del Deployment
  namespace: app-luis       # Namespace donde se desplegar치
spec:
  replicas: 1 # Cantidad de Pods a ejecutar
  selector:
    matchLabels:
      app: postgres # Selector para asociar Pods
  template:
    metadata:
      labels:
        app: postgres # Etiqueta que identifica este Pod
    spec:
      containers:
        - name: postgres
          image: postgres:14 # Imagen de PostgreSQL versi칩n 14
          ports:
            - containerPort: 5432 # Puerto en el contenedor donde PostgreSQL escucha
          env: # Variables de entorno para configurar PostgreSQL
            - name: POSTGRES_USER
              value: "luis"
            - name: POSTGRES_PASSWORD
              value: "luis01"
            - name: POSTGRES_DB
              value: "master"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data # Ruta donde se guardar치n los datos
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc # Asocia el PVC para la persistencia de datos

---
# Service para PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres-service # Nombre del servicio PostgreSQL
  namespace: app-luis    # Namespace donde se desplegar치
spec:
  selector:
    app: postgres # Selecciona los Pods con esta etiqueta
  ports:
    - protocol: TCP
      port: 5432      # Puerto expuesto por el servicio
      targetPort: 5432 # Puerto en el contenedor
  type: ClusterIP
